name: c_h_p
description: "Smart Paint Shop app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_database: ^12.0.3
  firebase_messaging: ^16.0.3
  firebase_storage: ^13.0.3
  flutter_local_notifications: ^19.5.0
  provider: ^6.1.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.6
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^7.0.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.1.1+1
  image_picker: ^1.0.7
  iconsax: ^0.0.8
  fluttertoast: ^8.2.1
  http: ^1.2.1
  flutter_colorpicker: ^1.1.0
  cached_network_image: ^3.3.1
  scrollable_positioned_list: ^0.3.8
  razorpay_flutter: ^1.3.6
  tab_indicator_styler: ^2.0.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  file_picker: ^10.3.3
  geolocator: ^13.0.4
  geocoding: ^4.0.0
  crop_your_image: ^1.1.0
  path_provider: ^2.1.3
  image: ^4.2.0
  ar_flutter_plugin_updated: ^0.0.1
  vector_math: ^2.1.4
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.5.1


  path: any
  uuid: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3

dependency_overrides:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/onboard2.jpeg
    - assets/onboard1.jpeg
    - assets/onboard3.jpeg
    - assets/logo.jpeg
    - assets/google.png
    - assets/color2.jpeg
    - assets/color3.jpeg
    - assets/delivery1.png
    - assets/delivery2.png
    - assets/delivery3.png
    - assets/image_b8a96a.jpg
    - assets/image_b8aca7.jpg
    - assets/image_b8b0ca.jpg
    - assets/image_c55c29.png
    - assets/image_b8b149.png
    - assets/image_b83903.png
    - assets/image_c505f5.png
    - assets/asian.jpg
    - assets/indigo.jpg
    - assets/ultima.jpg
    - assets/Apex.jpg
    - assets/Ace.jpg
    - assets/pack_size.jpeg
    - assets/painter.jpg
    - assets/calc.webp
